- hosts: localhost
  connection: local
  vars_files:
     - /home/rajgali83/accesskey
  tasks:
     - name: EC2 creation
       cloudformation:
          aws_access_key: "{{ accesskey }}"
          aws_secret_key: "{{ secretkey }}"
          stack_name: 'shivacf'
          state: present
          region: us-west-2
          #disable_rollback: true
          template: ./launch_config.template
          template_parameters:
             #CidrBlock: 10.10.12.0/24
             pubAvailabilityZone: us-west-2a
             #pubSubnetCIDR: 10.10.12.0/25
             privAvailabilityZone: us-west-2c
             #privSubnetCIDR: 10.10.12.128/25
             InstanceName: 'shivainfra' 
             #InstanceType: t2.micro
             KeyName: awscf
             Environment: DEV
             MaxSizeASG: 1
             MinSizeASG: 1
             DesiredCapacityASG: 1
             #InstancePublicIP: "True"
             #InstanceAMI: "ami-0d6621c01e8c2de2c"
             
